name             'mi_propia'
maintainer       'TechOps Solutions'
maintainer_email 'admin@example.com'
license          'All Rights Reserved'
description      'Cookbook propio para demostración / pruebas unitarias'
version          '0.1.0'
chef_version     '>= 14.0'
