name             'mi_mysql'
maintainer       'TechOps Solutions'
maintainer_email 'admin@example.com'
license          'All Rights Reserved'
description     ' cookbook'
version          '0.1.0'
chef_version    '>= 14.0'